/*
 *     
 * 
 */
package za.co.nemesisnet.supreme.invention.ClientPackages.view;

import java.awt.Image;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;


import za.co.nemesisnet.supreme.invention.model.*;

/**
 *
 * @author Peter Buckingham
 */
public class BookshelfDisplay extends javax.swing.JFrame {
 
    ArrayList<Book> bookList;
    ArrayList<User> userList;
    ArrayList<Message> messageList;
    ArrayList<Loan> loanList = new ArrayList<Loan>();

    User user;
    Message responseMessageObject;
    Object responseDataObject;

    GuiClientApp guiClientApp;
    /**
     * Creates new form UserListForm
     */
    public BookshelfDisplay() {
        setTitle("Client System" +" - " + "Bookshelf");
        initComponents();
    }

    public BookshelfDisplay(User user, ArrayList<Book> bookList,GuiClientApp guiClientApp) {
        setTitle("Client System" +" - " + "Bookshelf" );
        initComponents();
        this.guiClientApp = guiClientApp;
        this.bookList = bookList;
        this.user = user;
//        Message message  = new Message("LISTALLBOOKS");
//        
//       responseMessageObject =  guiClientApp.sendMessageData(message);
//       responseDataObject = guiClientApp.sendObjectData(bookList);
//        bookList = (ArrayList<Book>) responseDataObject;
        
        //loop though list to populate table
        // this.userList = userList;
        Object[][] data = new Object[bookList.size()][5];
        for (int i = 0; i < bookList.size(); i++) {

        //    data[i][0] = bookList.get(i).getBookId();
            // data[i][0] = i;
            data[i][0] = bookList.get(i).getISBN();
            data[i][1] = bookList.get(i).getTitle();
            data[i][2] = bookList.get(i).getAuthors();
            data[i][3] = bookList.get(i).getCategory();
            data[i][4] = bookList.get(i).isAvailableForLoan();
     //       data[i][5] = bookList.get(i).getRating();

        }

        Object[] columnNames = {"ISBN : ", "Title : ", "Author : ", "Category : ", "Available : "};
        DefaultTableModel model = new DefaultTableModel(data, columnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        jTable1.setModel(model);

// create JTable just once and pass model in the constructor
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelMid3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBottom = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jPanelTop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewLoan = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAddLearner = new javax.swing.JMenuItem();
        jMenuItemAddBook = new javax.swing.JMenuItem();
        jMenuEdit1 = new javax.swing.JMenu();
        jMenuItemLoanList = new javax.swing.JMenuItem();
        jMenuItemBookList = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jMenuItemHelpWiki = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(displayFrameImageIcon());
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanelMain.setBackground(new java.awt.Color(250, 249, 246));

        jPanelMid3.setBackground(new java.awt.Color(192, 192, 192));
        jPanelMid3.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Number", "Ttile", "Sub-Title", "Autor", "Description", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelMid3Layout = new javax.swing.GroupLayout(jPanelMid3);
        jPanelMid3.setLayout(jPanelMid3Layout);
        jPanelMid3Layout.setHorizontalGroup(
            jPanelMid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMid3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelMid3Layout.setVerticalGroup(
            jPanelMid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMid3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanelBottom.setBackground(new java.awt.Color(192, 192, 192));
        jPanelBottom.setForeground(new java.awt.Color(0, 0, 0));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonCancel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelTop.setBackground(new java.awt.Color(192, 192, 192));

        jLabel3.setBackground(new java.awt.Color(192, 192, 192));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bookshelf :");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMid3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuFile.setMnemonic('F');
        jMenuFile.setText("File");

        jMenuItemNewLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        jMenuItemNewLoan.setMnemonic('L');
        jMenuItemNewLoan.setText("New Loan");
        jMenuItemNewLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewLoanActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemNewLoan);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setMnemonic('e');
        jMenuEdit.setText("Crud");

        jMenuItemAddLearner.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        jMenuItemAddLearner.setMnemonic('u');
        jMenuItemAddLearner.setText("Add Learner");
        jMenuItemAddLearner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddLearnerActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemAddLearner);

        jMenuItemAddBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuItemAddBook.setMnemonic('c');
        jMenuItemAddBook.setText("Add Book");
        jMenuItemAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddBookActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemAddBook);

        jMenuBar1.add(jMenuEdit);

        jMenuEdit1.setMnemonic('e');
        jMenuEdit1.setText("Lists");

        jMenuItemLoanList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        jMenuItemLoanList.setMnemonic('u');
        jMenuItemLoanList.setText("List Loans");
        jMenuItemLoanList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoanListActionPerformed(evt);
            }
        });
        jMenuEdit1.add(jMenuItemLoanList);

        jMenuItemBookList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuItemBookList.setMnemonic('c');
        jMenuItemBookList.setText("List Books");
        jMenuItemBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookListActionPerformed(evt);
            }
        });
        jMenuEdit1.add(jMenuItemBookList);

        jMenuBar1.add(jMenuEdit1);

        jMenuHelp.setMnemonic('h');
        jMenuHelp.setText("Help");

        jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItemAbout.setMnemonic('a');
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuItemHelpWiki.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, 0));
        jMenuItemHelpWiki.setMnemonic('w');
        jMenuItemHelpWiki.setText("Help Wiki");
        jMenuItemHelpWiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpWikiActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpWiki);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println("table prints this");// TODO add your handling code here:
        String button = "none";
        System.out.println("Event trigered : " + evt);
        if (evt.getClickCount() == 2 && jTable1.getSelectedRow() != -1) {
            // your valueChanged overridden method 

            System.out.println(jTable1.getSelectedRow());
            // DisplayBookForm displayBookForm = new DisplayBookForm(bookList.get(jTable1.getSelectedRow()));
      //      Read read = new Read();
            Book book = bookList.get(jTable1.getSelectedRow());//book

            String userId = user.getUserId();

            System.out.println("Current User id : " +user.getUserId());
            

            System.out.println("Button is set to : "+button);
            //learner list
            

            DisplayBookForm displayBookForm = new DisplayBookForm(user, bookList.get(jTable1.getSelectedRow()), button);// means display loan buton
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemHelpWikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpWikiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemHelpWikiActionPerformed

    private void jMenuItemAddLearnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddLearnerActionPerformed
        // TODO add your handling code here:
        CreateLearnerForm createLearnerForm = new CreateLearnerForm(guiClientApp);
        createLearnerForm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAddLearnerActionPerformed

    private void jMenuItemAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddBookActionPerformed
        // TODO add your handling code here:
        CreateBookForm createBookForm = new CreateBookForm(guiClientApp);
        createBookForm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAddBookActionPerformed

    private void jMenuItemNewLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewLoanActionPerformed
        // TODO add your handling code here:
//        Read read = new Read();
//        //   DisplayBookForm displayBookForm = new DisplayBookForm(user, read.loanBookByTitle(), rootPaneCheckingEnabled);
//        BookingForm bookingForm = new BookingForm(user, read.loanBookByTitle());
//        bookingForm.setVisible(true);
//        bookingForm.setAutoRequestFocus(true);
          //prompt for studentnumber joptionpane that will be used to create a new loan via booking form
        //promt for book isbn
        //create new loan
            String studentNumber = JOptionPane.showInputDialog("Enter Student Number");
            //send student number to server
        Message message  = new Message();
        Message response = new Message();
        message.setText("FIND_LEARNER");
        response = guiClientApp.sendMessageData(message);
        System.out.println("Response from server : "+response.getText());
        Learner learner = new Learner();
        Learner learnerFromDatabase = new Learner();
        learner.setStudentNumber(Integer.parseInt(studentNumber));
        learnerFromDatabase = (Learner) guiClientApp.sendObjectData(learner);
        System.out.println("Learner from database : "+learnerFromDatabase.getStudentNumber());
        //send book isbn to server
        String bookIsbn = JOptionPane.showInputDialog("Enter Book ISBN");
        message = new Message();
        message.setText("FIND_BOOK");
        response = guiClientApp.sendMessageData(message);
        System.out.println("Response from server : "+response.getText());
        Book book = new Book();
        book.setISBN(bookIsbn);
        Book bookFromDatabase = new Book();
        bookFromDatabase = (Book) guiClientApp.sendObjectData(book);
        System.out.println("Book from database : "+bookFromDatabase.getISBN());
        //joptiopane to dispay both learner and book
        JOptionPane.showMessageDialog(null, "Learner : "+learnerFromDatabase.getStudentNumber()+"\nBook : "+bookFromDatabase.getISBN());


        //create new loan
        BookingForm bookingForm = new BookingForm(user, learnerFromDatabase, bookFromDatabase , guiClientApp);
        bookingForm.setVisible(true);


        //send learner to server









    }//GEN-LAST:event_jMenuItemNewLoanActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        SwingUtilities.updateComponentTreeUI(this);
        this.invalidate();
        this.validate();
        this.repaint();
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        SwingUtilities.updateComponentTreeUI(this);
        this.invalidate();
        this.validate();
        this.repaint();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void jMenuItemLoanListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoanListActionPerformed
        // TODO add your handling code here:
        Message message = new Message();
        message.setText("LIST_ALL_LOANS");
        Message response = guiClientApp.sendMessageData(message);

        System.out.println("Response from server : " + response.getText());
           ArrayList<Loan> loanListFromDatabase = new ArrayList<Loan>();
        loanListFromDatabase  = (ArrayList<Loan>) guiClientApp.sendObjectData(loanList);
        System.out.println("Loan list from database : " + loanListFromDatabase);
        if (loanListFromDatabase != null) {
            LoanListDisplay loanListDisplay = new LoanListDisplay(guiClientApp,loanListFromDatabase);
            loanListDisplay.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No loans found");
        }



        
        
        
    }//GEN-LAST:event_jMenuItemLoanListActionPerformed

    private void jMenuItemBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBookListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookshelfDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookshelfDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookshelfDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookshelfDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BookshelfDisplay().setVisible(true);
  //              Read read = new Read();
                //read.readAllBooks();
                //bookListForm = new BookListForm(read.readAllBooks());
                //  bookListForm.setVisible(true);
                //bookListForm.setAutoRequestFocus(rootPaneCheckingEnabled);
            }
        });
    }

    public Image displayFrameImageIcon() {
    //    FrameSettings frameSettings = new FrameSettings();
        return null;
    }

    public void exit() {
        JOptionPane.showMessageDialog(new JFrame(), "Thanks for using my program!  \n \n " + "Author : Peter Buckingham \n Student Number: ****65289 \n Date: May 2022", "Ubiquitous System - CRUD ", JOptionPane.INFORMATION_MESSAGE);
        System.out.println("");
        System.out.println("Thanks for using my program!");
        System.out.println("Author : Peter Buckingham \n");
        System.err.println("");
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuEdit1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAddBook;
    private javax.swing.JMenuItem jMenuItemAddLearner;
    private javax.swing.JMenuItem jMenuItemBookList;
    private javax.swing.JMenuItem jMenuItemHelpWiki;
    private javax.swing.JMenuItem jMenuItemLoanList;
    private javax.swing.JMenuItem jMenuItemNewLoan;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMid3;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
